version: '3.8'
services:
  symfony:
    build:
      context: ./.docker/symfony
      args:
        PHP_V: ${PHP_V:-8.2}
    container_name: parser-symfony
    working_dir: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_V: ${PHP_V:-8.2}
      PHP_IDE_CONFIG: serverName=${VIRTUAL_HOST:-parser}
      XDEBUG_MODE: "develop,debug"
      COMPOSER_HOME: /app
    volumes:
      - ./:/app
      - ./.docker/symfony/php-ini-overrides.ini:/etc/php/${PHP_V:-8.2}/fpm/conf.d/99-overrides.ini
    depends_on:
      - database

  mailcatcher:
    image: dockage/mailcatcher
    container_name: parser-mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
    depends_on:
      - symfony


  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:16-alpine
    container_name: parser-database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 8901:${POSTGRES_PORT:-5432}
    volumes:
      #- database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./.docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

###> doctrine/doctrine-bundle ###
#volumes:
#  database_data:
###< doctrine/doctrine-bundle ###
